### ISSUE TITLE
support for passing memory sizes

### ISSUE THREAD

**Issue by Guigui220D** [MasterQ32/zig-args#11]
Like `--buffer_size=5k` `--file_size=20G`
It's often useful to do that, instead of writing --file_size=50000000, many utilities have command line arguments where you pass a size.

**Comment by Guigui220D** [comment]
Should it be a separate type in the spec, or should usize or even any  integer type support the syntax?

**Comment by MasterQ32** [comment]
I think it's okay to accept it for any integer. Another option would be only to allow it for `usize`. I'm happy with both.
