### ISSUE TITLE
[Help] Helper functions

### ISSUE THREAD

**Issue by InfRandomness** [MasterQ32/zig-args#18]
Hello;

I am trying to create some helper functions to avoid having multiple occurences of parseForCurrentProcess() in my code but I'm having some troubles;
I have made that code but I am unsure of what I should replace the "return;" to

```
pub fn parseArgs(comptime Spec: type) !args.ParseArgsResult(Spec) {
    var errorCollectorGPA = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = errorCollectorGPA.deinit();

    var collection = args.ErrorCollection.init(&errorCollectorGPA.allocator);
    defer _ = collection.deinit();
    
    const ops = args.parseForCurrentProcess(Spec, std.heap.page_allocator, args.ErrorHandling{ .collect = &collection }) catch {
        for (collection.errors()) |err| {
            try std.io.getStdOut().writer().print("{}\n", .{err});
        }
        return;
    };
    return ops;
}
```

The compiler returns me 
```
error: expected type '.args.ParseArgsResult(struct:9:32)', found 'void'
        return;
        ^
```

**Comment by MasterQ32** [comment]
You have to return either `args.ParseArgsResult(Spec)` or an error from your function. At least that's what you have declared in your function header.

What should happen in the case of a parsing error? Should the application continue happily? Should it crash? Clean exit?

**Comment by InfRandomness** [comment]
I think it would be better for it to crash because those arguments are required, without them, the rest of the code cannot do anything

**Comment by MasterQ32** [comment]
then just put ta `@panic("Invalid arguments")` there. But note that this will (for example) popup crash messages of the OS that the application crashed unexpectedly.
A clean exit can be achieved with `std.os.exit(1)` which will return a failure to the OS, but not a crash

**Comment by InfRandomness** [comment]
Oh, alright, a failure is okay too, as long as it does not return 0;
Thanks !
