### ISSUE TITLE
Compilation error: found '?std.process.NextError![:0]u8'

### ISSUE THREAD

**Issue by ShuP1** [MasterQ32/zig-args#22]
Hi, I'm using Zig 0.9.0 (linux binary release)

`std.process.ArgIterator.next` probably changed recently. Now requiring an allocator and returning optional error or allocated string.

using ``
```
./.zigmod/deps/git/github.com/MasterQ32/zig-args/args.zig:42:43: error: expected error union type, found '?std.process.NextError![:0]u8'
    const executable_name = (try args.next(allocator)) orelse {
```
Every call to `next` is broken.

**Comment by ShuP1** [comment]
Fix for my use-case. Probably no complete nor leak safe.
https://github.com/CalmSystem/zig-args/commit/fc421aff12a083c7da145df382a22bbbe97804c6

**Comment by ShuP1** [comment]
Actual implementation seems to match master.
https://github.com/ziglang/zig/commit/7e16bb36d82cf45cd5f6f4da38fba512554f66ed

**Comment by MasterQ32** [comment]
You can use the `zig-0.9.0` tag for this
