### ISSUE TITLE
Allow for shadowing a global flag

### ISSUE THREAD

**Issue by dgbuckley** [MasterQ32/zig-args#33]
It would be useful to shadow a global help flag. It may be useful to shadow any global flag, but I've only needed -h,--help.

To print the app's help message:
```sh
app -h verb
```

And the verb help message with:
```sh
app verb -h
```

**Comment by MasterQ32** [comment]
Why do you need shadowing for that?
```zig
if(cli.options.help and cli.verb == null) {

}
```

will solve the problem quite well imho

**Comment by dgbuckley** [comment]
That is a good point. It still seems nice if you could determine if help was before/after the verb but until I have a better reason to need that, this solution will work for me.

**Comment by MasterQ32** [comment]
>  It still seems nice if you could determine if help was before/after the verb

Please do not do such things, it's a super awkward user experience and completly non-obvious. Function aliasing is bad
